# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f330895004e5ba6f3a96b88cace288ef2eeaa6511a2df1edae6046ebf167703b3d5a76d65bc490d5a96e98a2c93a463d43a174eafa0517f353b84d0aabc91306

test:
  secret_key_base: f82847a3340c714c522983c9e543ffaf5c68d4212f54243bc6e45ea062ee97246c5fc75e6e9b2a06d073301160d98661976bed57827cebce4b09fab3bef9ff5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
